name: Check member exists in GitHub Team

description: 'GitHub Actions to check if an username exists in Team'

branding:
  icon: 'users'
  color: 'red'

inputs:
  org_slug:
    description: Name of the organization
    required: true
  team_slug:
    description: Name of Team to check
    required: true
  gh_token:
    description: GitHub Token with right permission
    required: true
  username:
    description: Type username to check
    required: true
   
outputs:
  exists-in-team: 
    description: If the member exists in the team
    value: ${{ steps.exists-team.outputs.exists-in-team }}

runs:
  using: composite
  steps:
    - id: exists-team
      shell: bash
      run: |
        EXIST_TEAM=$(curl -s -w "%{http_code}\n" -o /dev/null \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $GH_TOKEN" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/orgs/"$ORG"/teams/"$TEAM"/memberships/"$USERNAME")

        if [[ "$EXIST_TEAM" -eq 200 ]]; then
          echo "exists-in-team=true" >> $GITHUB_OUTPUT
        else
          echo "exists-in-team=false" >> $GITHUB_OUTPUT
        fi
      env:
        ORG: ${{ inputs.org_slug }}
        TEAM: ${{ inputs.team_slug }}
        GH_TOKEN: ${{ inputs.gh_token }}
        USERNAME: ${{ inputs.username }}
